name: app_template                     # 项目名称
description: "A new Flutter project."  # 项目名称
publish_to: 'none'                     # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

#环境
environment:
  sdk: '>=3.2.3 <4.0.0'


#生产环境依赖
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  json_annotation: any
  dio: ^5.0.3
  dio_http2_adapter: ^2.4.0
  dio_smart_retry: ^5.0.0
  dio_cache_interceptor: ^3.5.0
  device_info_plus: ^9.1.1
  flutter_overboard: ^3.1.3
  curved_navigation_bar: ^1.0.3 #latest version
  fancy_bottom_navigation: ^0.3.2   #注意: 这个包出现问题时，要修改：用 clipBehavior: Clip.none替换为overflow: Overflow.visible
  bubble_bottom_bar: ^2.0.0  #注意要解决：Badge在Badge.dart和material.dart中命名冲突问题，解决方法：隐藏掉material.dart中的Badge 即：....hide Badge
  convex_bottom_bar: ^3.2.0
  rolling_bottom_bar: ^0.2.2
  flutter_floating_bottom_bar: ^1.2.0
  water_drop_nav_bar: ^2.2.0+5
  molten_navigationbar_flutter: ^1.0.1
  flutter_snake_navigationbar: ^0.6.1
  dropdown_button2: ^2.3.8
  easy_localization: ^3.0.3
  battery_plus: ^5.0.2
  sensors_plus: ^4.0.2
  network_info_plus: ^4.1.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  flex_color_scheme: ^7.3.1
  google_fonts: 6.1.0
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.6.0
  flutter_login_template: ^1.1.0
  animations: ^2.0.11
  flutter_svg: ^1.1.0
  cupertino_icons: ^1.0.5
  animate_do: ^3.3.4
  material_dialogs: ^1.1.4
  flutter_easyloading: ^3.0.5
  bottom_bar_with_sheet: ^2.4.0
  floating_bottom_bar: ^0.0.1
  bottom_sheet_scaffold: ^0.1.9
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_swiper_null_safety: ^1.0.2
  bruno: ^3.4.3
  floating_bottom_navigation_bar: ^1.5.2
  flutter_speed_dial: ^7.0.0
  fluent_ui: ^4.8.4
  system_theme: ^2.3.1
  bitsdojo_window: ^0.1.6
  get: ^4.6.6
  macos_ui: ^2.0.2
  sliding_up_panel: ^2.0.0+1
  flutter_screenutil: ^5.9.0
  upgrader: ^10.3.0
  flutter_screen_lock: ^9.0.4
  local_auth: ^2.1.8
  native_auth: ^1.0.6
  secure_app_switcher: ^0.1.0+1
  responsive_builder: ^0.7.0
  web_socket_channel: ^2.4.0
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.23
  path_provider: ^2.1.3
  path: ^1.8.3
  responsive_framework: ^1.4.0
  flutter_adaptive_scaffold: ^0.1.10+2
  flutter_chat_ui: ^1.6.12
  file_picker: ^8.0.0+1
  open_filex: ^4.4.0
  image_picker: ^1.0.8
  draggable_bottom_sheet: ^1.0.2
  flutter_platform_widgets: ^6.1.0
  flutter_form_builder: ^9.2.1
  chat_bubbles: ^1.5.0
  flutter_chat_bubble: ^2.0.2
  smooth_sheets: ^0.7.3
  buttons_tabbar: ^1.3.10
  emoji_picker_flutter: ^2.1.1
  crypto: ^3.0.3
  social_media_recorder: ^1.1.13
  flutter_slidable: ^3.1.0
  drift_sqflite: ^2.0.1
  avatar_glow: ^3.0.1
  random_avatar: ^0.0.7
  starlight_popup_menu: ^0.0.3+1
  popup_menu_plus: ^0.0.6
  safe_device: ^1.1.7
  lan_scanner: ^4.0.0+1
  flutter_isolate: ^2.0.5-pre
  json_cache: ^3.0.1
  encryptor: ^0.0.1
  encrypt: ^5.0.3
  web_socket_client: ^0.1.0
  chalkdart: ^2.2.1
  uuid: ^3.0.6
  pretty_qr_code: ^3.3.0
  mobile_scanner: ^4.0.1
  quickalert: ^1.1.0









#开发环境依赖
dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  json_model: ^1.0.0
  json_serializable: any
  build_runner: ^2.4.9
  build_runner_core: ^7.2.9
  test: ^1.16.0
  pretty_dio_logger: ^1.3.1
  talker_dio_logger: ^2.4.0
  drift_dev: ^2.15.0
  source_gen: ^1.0.0
  hive_generator: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # 配置文件
  assets:
    - assets/App.json
    - assets/translations/
    - assets/introduction_animation/
    - assets/images/
    - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700